import type { Metadata } from 'next';
import { ibmPlexMono, plusJakartaSans } from '../../web/assets/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${plusJakartaSans.variable} ${ibmPlexMono.variable}`}
    >
      <body className='bg-background text-foreground min-h-screen'>
        <main
          id='main'
          className='min-h-screen'
        >
          {children}
        </main>
      </body>
    </html>
  );
}
